# config/packages/easy_admin.yaml
easy_admin:
  
  entities:
    Country:
      # ...
      list:
        fields:
          - { property: 'flag', type: 'flag', base_path: '%flag_images%' }
      # ...
      show:
        fields:
          - { property: 'flag', type: 'flag', base_path: '%flag_images%' }
    Agent:
      # ...
      list:
        fields:
          - { property: 'avatar', type: 'avatar', base_path: '%avatar_images%' }
      # ...
      show:
        fields:
          - { property: 'avatar', type: 'avatar', base_path: '%avatar_images%' }
