vich_uploader:
    db_driver: orm

    mappings:
        avatar_images:
            uri_prefix: '%avatar_images%'
            upload_destination: '%kernel.project_dir%/public%avatar_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: true
            delete_on_remove: true
