vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:

        avatar_images:
            uri_prefix: '%avatar_images%'
            upload_destination: '%kernel.project_dir%/public%avatar_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: true

        flag_images:
            uri_prefix: '%flag_images%'
            upload_destination: '%kernel.project_dir%/public%flag_images%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_update: false
            delete_on_remove: true